### ISSUE TITLE
how raindrop removal neural network works? 

### ISSUE THREAD

**Issue by aalzooke** [rui1996/rui1996.github.io#1]
I'm doing a similar project, can you explain how are you apportion this method? 
Thank you

**Comment by rui1996** [comment]
The neural network is learning a kind of image-to-image translation which transform the raindrop degraded input to a clean output.

**Comment by aalzooke** [comment]
Can you please share your implantation. 
Thank you

**Comment by rui1996** [comment]
You can find the code/demo here: https://github.com/rui1996/DeRaindrop

**Comment by aalzooke** [comment]
Thank you so much for your help
